#use_frameworks!

target 'ADXLibrary_Example' do
  target 'ADXLibrary_Tests' do
    inherit! :search_paths
        
#    pod 'FBSnapshotTestCase'
    pod 'MobFoxSDK', :git => 'https://github.com/mobfox/MobFox-iOS-SDK.git'
  end
  pod 'ADXLibrary', :path => '../'
end
